//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.34209
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniOPI.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CHS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CHS() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniOPI.Properties.CHS", typeof(CHS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 警报记录 的當地語系化字串。
        /// </summary>
        internal static string D_AlarmHistory {
            get {
                return ResourceManager.GetString("D_AlarmHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警报管理 的當地語系化字串。
        /// </summary>
        internal static string D_AlarmManagement {
            get {
                return ResourceManager.GetString("D_AlarmManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警报状态 的當地語系化字串。
        /// </summary>
        internal static string D_AlarmStatus {
            get {
                return ResourceManager.GetString("D_AlarmStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 APC 下载管理 的當地語系化字串。
        /// </summary>
        internal static string D_APCDownloadManagement {
            get {
                return ResourceManager.GetString("D_APCDownloadManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 APC 上报管理 的當地語系化字串。
        /// </summary>
        internal static string D_APCReportManagement {
            get {
                return ResourceManager.GetString("D_APCReportManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Buffer RW Judge Capacity 的當地語系化字串。
        /// </summary>
        internal static string D_BufferRWJudgeCapacity {
            get {
                return ResourceManager.GetString("D_BufferRWJudgeCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 卡匣记录 的當地語系化字串。
        /// </summary>
        internal static string D_CassetteHistory {
            get {
                return ResourceManager.GetString("D_CassetteHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Changer Plan 的當地語系化字串。
        /// </summary>
        internal static string D_ChangerPlan {
            get {
                return ResourceManager.GetString("D_ChangerPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CIM Message 的當地語系化字串。
        /// </summary>
        internal static string D_CIMMessage {
            get {
                return ResourceManager.GetString("D_CIMMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CIM Message History 的當地語系化字串。
        /// </summary>
        internal static string D_CIMMessageHistory {
            get {
                return ResourceManager.GetString("D_CIMMessageHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CIM Message Management 的當地語系化字串。
        /// </summary>
        internal static string D_CIMMessageManagement {
            get {
                return ResourceManager.GetString("D_CIMMessageManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CIM Mode 的當地語系化字串。
        /// </summary>
        internal static string D_CIMMode {
            get {
                return ResourceManager.GetString("D_CIMMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Daily Check 的當地語系化字串。
        /// </summary>
        internal static string D_DailyCheck {
            get {
                return ResourceManager.GetString("D_DailyCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Daily Check History 的當地語系化字串。
        /// </summary>
        internal static string D_DailyCheckHistory {
            get {
                return ResourceManager.GetString("D_DailyCheckHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Daily Check Management 的當地語系化字串。
        /// </summary>
        internal static string D_DailyCheckManagement {
            get {
                return ResourceManager.GetString("D_DailyCheckManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Defect Code History 的當地語系化字串。
        /// </summary>
        internal static string D_DefectCodeHistory {
            get {
                return ResourceManager.GetString("D_DefectCodeHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Defect Code Report 的當地語系化字串。
        /// </summary>
        internal static string D_DefectCodeReport {
            get {
                return ResourceManager.GetString("D_DefectCodeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 删除/还原WIP 的當地語系化字串。
        /// </summary>
        internal static string D_DeleteWIP {
            get {
                return ResourceManager.GetString("D_DeleteWIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Each Position 的當地語系化字串。
        /// </summary>
        internal static string D_EachPosition {
            get {
                return ResourceManager.GetString("D_EachPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 能源可视化 的當地語系化字串。
        /// </summary>
        internal static string D_EnergyVisualization {
            get {
                return ResourceManager.GetString("D_EnergyVisualization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Energy Visualization Management 的當地語系化字串。
        /// </summary>
        internal static string D_EnergyVisualizationManagement {
            get {
                return ResourceManager.GetString("D_EnergyVisualizationManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Equipment Fetch Glass Proportional Rule 的當地語系化字串。
        /// </summary>
        internal static string D_EquipmentFetchGlassProportional {
            get {
                return ResourceManager.GetString("D_EquipmentFetchGlassProportional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Equipment Fetch Glass Proportional Rule Command 的當地語系化字串。
        /// </summary>
        internal static string D_EquipmentFetchGlassProportionalCommand {
            get {
                return ResourceManager.GetString("D_EquipmentFetchGlassProportionalCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Force Clean Out 的當地語系化字串。
        /// </summary>
        internal static string D_ForceCleanOut {
            get {
                return ResourceManager.GetString("D_ForceCleanOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Help 的當地語系化字串。
        /// </summary>
        internal static string D_Help {
            get {
                return ResourceManager.GetString("D_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 记录 的當地語系化字串。
        /// </summary>
        internal static string D_History {
            get {
                return ResourceManager.GetString("D_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Indexer Operation Mode 的當地語系化字串。
        /// </summary>
        internal static string D_IndexerOperationMode {
            get {
                return ResourceManager.GetString("D_IndexerOperationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Ionizer Fan Mode 的當地語系化字串。
        /// </summary>
        internal static string D_IonizerFanMode {
            get {
                return ResourceManager.GetString("D_IonizerFanMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Job Count 的當地語系化字串。
        /// </summary>
        internal static string D_JobCount {
            get {
                return ResourceManager.GetString("D_JobCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Job History 的當地語系化字串。
        /// </summary>
        internal static string D_JobHistory {
            get {
                return ResourceManager.GetString("D_JobHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 配置 的當地語系化字串。
        /// </summary>
        internal static string D_Layout {
            get {
                return ResourceManager.GetString("D_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 连接控制 的當地語系化字串。
        /// </summary>
        internal static string D_LineControl {
            get {
                return ResourceManager.GetString("D_LineControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 连接记录 的當地語系化字串。
        /// </summary>
        internal static string D_LineHistory {
            get {
                return ResourceManager.GetString("D_LineHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 连接信息 的當地語系化字串。
        /// </summary>
        internal static string D_LineInformation {
            get {
                return ResourceManager.GetString("D_LineInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 连接模式 的當地語系化字串。
        /// </summary>
        internal static string D_LineMode {
            get {
                return ResourceManager.GetString("D_LineMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 连接特例 的當地語系化字串。
        /// </summary>
        internal static string D_LineSpecial {
            get {
                return ResourceManager.GetString("D_LineSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 连接规则 的當地語系化字串。
        /// </summary>
        internal static string D_LineStatusRule {
            get {
                return ResourceManager.GetString("D_LineStatusRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 连接状态 的當地語系化字串。
        /// </summary>
        internal static string D_LinkStatus {
            get {
                return ResourceManager.GetString("D_LinkStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Material History 的當地語系化字串。
        /// </summary>
        internal static string D_MaterialHistory {
            get {
                return ResourceManager.GetString("D_MaterialHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Material Status 的當地語系化字串。
        /// </summary>
        internal static string D_MaterialStatus {
            get {
                return ResourceManager.GetString("D_MaterialStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MES Alive Request 的當地語系化字串。
        /// </summary>
        internal static string D_MESConnectionTest {
            get {
                return ResourceManager.GetString("D_MESConnectionTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Monitor 的當地語系化字串。
        /// </summary>
        internal static string D_Monitor {
            get {
                return ResourceManager.GetString("D_Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 EQP Control 的當地語系化字串。
        /// </summary>
        internal static string D_NodeControl {
            get {
                return ResourceManager.GetString("D_NodeControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 EQP History 的當地語系化字串。
        /// </summary>
        internal static string D_NodeHistory {
            get {
                return ResourceManager.GetString("D_NodeHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 EQP Status 的當地語系化字串。
        /// </summary>
        internal static string D_NodeStatus {
            get {
                return ResourceManager.GetString("D_NodeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ODF Assembly History 的當地語系化字串。
        /// </summary>
        internal static string D_ODFAssemblyHistory {
            get {
                return ResourceManager.GetString("D_ODFAssemblyHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ODF Track Time 修改 的當地語系化字串。
        /// </summary>
        internal static string D_ODFTrackTimeSetting {
            get {
                return ResourceManager.GetString("D_ODFTrackTimeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Operation 的當地語系化字串。
        /// </summary>
        internal static string D_Operator {
            get {
                return ResourceManager.GetString("D_Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OPI History 的當地語系化字串。
        /// </summary>
        internal static string D_OPIHistory {
            get {
                return ResourceManager.GetString("D_OPIHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Parameter 的當地語系化字串。
        /// </summary>
        internal static string D_Parameter {
            get {
                return ResourceManager.GetString("D_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Parameter Setting 的當地語系化字串。
        /// </summary>
        internal static string D_ParameterSetting {
            get {
                return ResourceManager.GetString("D_ParameterSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ELA Parameter Setting 的當地語系化字串。
        /// </summary>
        internal static string D_ParameterSetting_ELA {
            get {
                return ResourceManager.GetString("D_ParameterSetting_ELA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PLC TRX Data 的當地語系化字串。
        /// </summary>
        internal static string D_PLCTrxData {
            get {
                return ResourceManager.GetString("D_PLCTrxData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Port Control 的當地語系化字串。
        /// </summary>
        internal static string D_PortControl {
            get {
                return ResourceManager.GetString("D_PortControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Port History 的當地語系化字串。
        /// </summary>
        internal static string D_PortHistory {
            get {
                return ResourceManager.GetString("D_PortHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Port Status 的當地語系化字串。
        /// </summary>
        internal static string D_PortStatus {
            get {
                return ResourceManager.GetString("D_PortStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Process Data 的當地語系化字串。
        /// </summary>
        internal static string D_ProcessData {
            get {
                return ResourceManager.GetString("D_ProcessData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Process Data History 的當地語系化字串。
        /// </summary>
        internal static string D_ProcessDataHistory {
            get {
                return ResourceManager.GetString("D_ProcessDataHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Process Data Management 的當地語系化字串。
        /// </summary>
        internal static string D_ProcessDataManagement {
            get {
                return ResourceManager.GetString("D_ProcessDataManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Product Type Block 的當地語系化字串。
        /// </summary>
        internal static string D_ProductTypeBlock {
            get {
                return ResourceManager.GetString("D_ProductTypeBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Q Time Setting 的當地語系化字串。
        /// </summary>
        internal static string D_QTimeSetting {
            get {
                return ResourceManager.GetString("D_QTimeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Real Time Glass Count 的當地語系化字串。
        /// </summary>
        internal static string D_RealTimeGlassCount {
            get {
                return ResourceManager.GetString("D_RealTimeGlassCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Recipe List 的當地語系化字串。
        /// </summary>
        internal static string D_RecipeList {
            get {
                return ResourceManager.GetString("D_RecipeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Recipe Management 的當地語系化字串。
        /// </summary>
        internal static string D_RecipeManagement {
            get {
                return ResourceManager.GetString("D_RecipeManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cross Line Recipe Management 的當地語系化字串。
        /// </summary>
        internal static string D_RecipeManagementCross {
            get {
                return ResourceManager.GetString("D_RecipeManagementCross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Recipe Paramater History 的當地語系化字串。
        /// </summary>
        internal static string D_RecipeParamaterHistory {
            get {
                return ResourceManager.GetString("D_RecipeParamaterHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Recipe Parameter 的當地語系化字串。
        /// </summary>
        internal static string D_RecipeParameter {
            get {
                return ResourceManager.GetString("D_RecipeParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cross Line Recipe Parameter 的當地語系化字串。
        /// </summary>
        internal static string D_RecipeParameterCross {
            get {
                return ResourceManager.GetString("D_RecipeParameterCross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Recipe Parameter Management 的當地語系化字串。
        /// </summary>
        internal static string D_RecipeParameterManagement {
            get {
                return ResourceManager.GetString("D_RecipeParameterManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cross Line Recipe Register 的當地語系化字串。
        /// </summary>
        internal static string D_RecipeRegisterCorss {
            get {
                return ResourceManager.GetString("D_RecipeRegisterCorss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Recipe Table History 的當地語系化字串。
        /// </summary>
        internal static string D_RecipeTableHistory {
            get {
                return ResourceManager.GetString("D_RecipeTableHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Robot Control 的當地語系化字串。
        /// </summary>
        internal static string D_RobotControl {
            get {
                return ResourceManager.GetString("D_RobotControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 RobotLayout 的當地語系化字串。
        /// </summary>
        internal static string D_RobotLayout {
            get {
                return ResourceManager.GetString("D_RobotLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Robot Management 的當地語系化字串。
        /// </summary>
        internal static string D_RobotManagement {
            get {
                return ResourceManager.GetString("D_RobotManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Robot Method Definition 的當地語系化字串。
        /// </summary>
        internal static string D_RobotMethodDef {
            get {
                return ResourceManager.GetString("D_RobotMethodDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Robot Route 的當地語系化字串。
        /// </summary>
        internal static string D_RobotRoute {
            get {
                return ResourceManager.GetString("D_RobotRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Robot Route Condition 的當地語系化字串。
        /// </summary>
        internal static string D_RobotRouteCondition {
            get {
                return ResourceManager.GetString("D_RobotRouteCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Robot Route Master 的當地語系化字串。
        /// </summary>
        internal static string D_RobotRouteMst {
            get {
                return ResourceManager.GetString("D_RobotRouteMst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Robot Rule Job Select 的當地語系化字串。
        /// </summary>
        internal static string D_RobotRuleJobSelect {
            get {
                return ResourceManager.GetString("D_RobotRuleJobSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Robot Run Mode Management 的當地語系化字串。
        /// </summary>
        internal static string D_RobotRunModeManagement {
            get {
                return ResourceManager.GetString("D_RobotRunModeManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Robot Stage Management 的當地語系化字串。
        /// </summary>
        internal static string D_RobotStageManagement {
            get {
                return ResourceManager.GetString("D_RobotStageManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Run Mode 的當地語系化字串。
        /// </summary>
        internal static string D_RunMode {
            get {
                return ResourceManager.GetString("D_RunMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 抽检规则 的當地語系化字串。
        /// </summary>
        internal static string D_SamplingRule {
            get {
                return ResourceManager.GetString("D_SamplingRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SECS 功能 的當地語系化字串。
        /// </summary>
        internal static string D_SECSFunction {
            get {
                return ResourceManager.GetString("D_SECSFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SECS Variable Management 的當地語系化字串。
        /// </summary>
        internal static string D_SECSVariableManagement {
            get {
                return ResourceManager.GetString("D_SECSVariableManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 设置 的當地語系化字串。
        /// </summary>
        internal static string D_Setting {
            get {
                return ResourceManager.GetString("D_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Skip Report Setting 的當地語系化字串。
        /// </summary>
        internal static string D_SkipReportSetting {
            get {
                return ResourceManager.GetString("D_SkipReportSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Slot 信息 的當地語系化字串。
        /// </summary>
        internal static string D_SlotInformation {
            get {
                return ResourceManager.GetString("D_SlotInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sub Block 的當地語系化字串。
        /// </summary>
        internal static string D_SubBlock {
            get {
                return ResourceManager.GetString("D_SubBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Time Calibration 的當地語系化字串。
        /// </summary>
        internal static string D_TimeCalibration {
            get {
                return ResourceManager.GetString("D_TimeCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Time Calivration 的當地語系化字串。
        /// </summary>
        internal static string D_TimeCalivration {
            get {
                return ResourceManager.GetString("D_TimeCalivration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Track Out 的當地語系化字串。
        /// </summary>
        internal static string D_TrackOut {
            get {
                return ResourceManager.GetString("D_TrackOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unit History 的當地語系化字串。
        /// </summary>
        internal static string D_UnitHistory {
            get {
                return ResourceManager.GetString("D_UnitHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unloading Port Setting 的當地語系化字串。
        /// </summary>
        internal static string D_UnloadingPortSetting {
            get {
                return ResourceManager.GetString("D_UnloadingPortSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 User Account 的當地語系化字串。
        /// </summary>
        internal static string D_UserAccount {
            get {
                return ResourceManager.GetString("D_UserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密码修改 的當地語系化字串。
        /// </summary>
        internal static string D_UserChangePwd {
            get {
                return ResourceManager.GetString("D_UserChangePwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 用户组 的當地語系化字串。
        /// </summary>
        internal static string D_UserGroup {
            get {
                return ResourceManager.GetString("D_UserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 User Group Query 的當地語系化字串。
        /// </summary>
        internal static string D_UserGroupQuery {
            get {
                return ResourceManager.GetString("D_UserGroupQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 用户登录 的當地語系化字串。
        /// </summary>
        internal static string D_UserLogin {
            get {
                return ResourceManager.GetString("D_UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 VCR ON 的當地語系化字串。
        /// </summary>
        internal static string D_VCRReaderON {
            get {
                return ResourceManager.GetString("D_VCRReaderON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 VCR  的當地語系化字串。
        /// </summary>
        internal static string D_VCRStatus {
            get {
                return ResourceManager.GetString("D_VCRStatus", resourceCulture);
            }
        }
    }
}
