//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniOPI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ENG {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ENG() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniOPI.Properties.ENG", typeof(ENG).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abnormal Force Clean Out.
        /// </summary>
        internal static string D_AbnormalForceCleanOut {
            get {
                return ResourceManager.GetString("D_AbnormalForceCleanOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm History.
        /// </summary>
        internal static string D_AlarmHistory {
            get {
                return ResourceManager.GetString("D_AlarmHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Management.
        /// </summary>
        internal static string D_AlarmManagement {
            get {
                return ResourceManager.GetString("D_AlarmManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Status.
        /// </summary>
        internal static string D_AlarmStatus {
            get {
                return ResourceManager.GetString("D_AlarmStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APC Data.
        /// </summary>
        internal static string D_APCData {
            get {
                return ResourceManager.GetString("D_APCData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APC Download Management.
        /// </summary>
        internal static string D_APCDownloadManagement {
            get {
                return ResourceManager.GetString("D_APCDownloadManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APC Report Management.
        /// </summary>
        internal static string D_APCReportManagement {
            get {
                return ResourceManager.GetString("D_APCReportManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You There Request.
        /// </summary>
        internal static string D_AreYouThereRequest {
            get {
                return ResourceManager.GetString("D_AreYouThereRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer RW Judge Capacity.
        /// </summary>
        internal static string D_BufferRWJudgeCapacity {
            get {
                return ResourceManager.GetString("D_BufferRWJudgeCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cassette History.
        /// </summary>
        internal static string D_CassetteHistory {
            get {
                return ResourceManager.GetString("D_CassetteHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cassette on Port Q Time.
        /// </summary>
        internal static string D_CassetteonPortQTime {
            get {
                return ResourceManager.GetString("D_CassetteonPortQTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Cassette on Port Q Time.
        /// </summary>
        internal static string D_CassetteonPortQTimeNEW {
            get {
                return ResourceManager.GetString("D_CassetteonPortQTimeNEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Line Special Check.
        /// </summary>
        internal static string D_CellLineSpecialCheck {
            get {
                return ResourceManager.GetString("D_CellLineSpecialCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changer Plan.
        /// </summary>
        internal static string D_ChangerPlan {
            get {
                return ResourceManager.GetString("D_ChangerPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIM Message.
        /// </summary>
        internal static string D_CIMMessage {
            get {
                return ResourceManager.GetString("D_CIMMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIM Message History.
        /// </summary>
        internal static string D_CIMMessageHistory {
            get {
                return ResourceManager.GetString("D_CIMMessageHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIM Message Management.
        /// </summary>
        internal static string D_CIMMessageManagement {
            get {
                return ResourceManager.GetString("D_CIMMessageManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIM Mode.
        /// </summary>
        internal static string D_CIMMode {
            get {
                return ResourceManager.GetString("D_CIMMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cool Run Remain Count.
        /// </summary>
        internal static string D_CoolRunRemainCount {
            get {
                return ResourceManager.GetString("D_CoolRunRemainCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cool Run Set Count.
        /// </summary>
        internal static string D_CoolRunSetCount {
            get {
                return ResourceManager.GetString("D_CoolRunSetCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Cool Run Count.
        /// </summary>
        internal static string D_CoolRunSetCountNew {
            get {
                return ResourceManager.GetString("D_CoolRunSetCountNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Check.
        /// </summary>
        internal static string D_DailyCheck {
            get {
                return ResourceManager.GetString("D_DailyCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Check History.
        /// </summary>
        internal static string D_DailyCheckHistory {
            get {
                return ResourceManager.GetString("D_DailyCheckHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Check Management.
        /// </summary>
        internal static string D_DailyCheckManagement {
            get {
                return ResourceManager.GetString("D_DailyCheckManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect Code History.
        /// </summary>
        internal static string D_DefectCodeHistory {
            get {
                return ResourceManager.GetString("D_DefectCodeHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect Code Report.
        /// </summary>
        internal static string D_DefectCodeReport {
            get {
                return ResourceManager.GetString("D_DefectCodeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIP Delete/Recovery.
        /// </summary>
        internal static string D_DeleteWIP {
            get {
                return ResourceManager.GetString("D_DeleteWIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each Position.
        /// </summary>
        internal static string D_EachPosition {
            get {
                return ResourceManager.GetString("D_EachPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy Visualization.
        /// </summary>
        internal static string D_EnergyVisualization {
            get {
                return ResourceManager.GetString("D_EnergyVisualization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy Visualization Management.
        /// </summary>
        internal static string D_EnergyVisualizationManagement {
            get {
                return ResourceManager.GetString("D_EnergyVisualizationManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Fetch Glass Proportional Rule.
        /// </summary>
        internal static string D_EquipmentFetchGlassProportional {
            get {
                return ResourceManager.GetString("D_EquipmentFetchGlassProportional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Fetch Glass Proportional Rule Command.
        /// </summary>
        internal static string D_EquipmentFetchGlassProportionalCommand {
            get {
                return ResourceManager.GetString("D_EquipmentFetchGlassProportionalCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Fab Type.
        /// </summary>
        internal static string D_FabType {
            get {
                return ResourceManager.GetString("D_FabType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory Type.
        /// </summary>
        internal static string D_FactoryType {
            get {
                return ResourceManager.GetString("D_FactoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Clean Out.
        /// </summary>
        internal static string D_ForceCleanOut {
            get {
                return ResourceManager.GetString("D_ForceCleanOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glass Grade Mapping.
        /// </summary>
        internal static string D_GlassGradeMapping {
            get {
                return ResourceManager.GetString("D_GlassGradeMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string D_Help {
            get {
                return ResourceManager.GetString("D_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string D_History {
            get {
                return ResourceManager.GetString("D_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexer Operation Mode.
        /// </summary>
        internal static string D_IndexerOperationMode {
            get {
                return ResourceManager.GetString("D_IndexerOperationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection Idle Time Setting.
        /// </summary>
        internal static string D_InspectionIdleTimeSetting {
            get {
                return ResourceManager.GetString("D_InspectionIdleTimeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ionizer Fan Mode.
        /// </summary>
        internal static string D_IonizerFanMode {
            get {
                return ResourceManager.GetString("D_IonizerFanMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Count.
        /// </summary>
        internal static string D_JobCount {
            get {
                return ResourceManager.GetString("D_JobCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job History.
        /// </summary>
        internal static string D_JobHistory {
            get {
                return ResourceManager.GetString("D_JobHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        internal static string D_Layout {
            get {
                return ResourceManager.GetString("D_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Control.
        /// </summary>
        internal static string D_LineControl {
            get {
                return ResourceManager.GetString("D_LineControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line History.
        /// </summary>
        internal static string D_LineHistory {
            get {
                return ResourceManager.GetString("D_LineHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line ID.
        /// </summary>
        internal static string D_LineID {
            get {
                return ResourceManager.GetString("D_LineID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Information.
        /// </summary>
        internal static string D_LineInformation {
            get {
                return ResourceManager.GetString("D_LineInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Mode.
        /// </summary>
        internal static string D_LineMode {
            get {
                return ResourceManager.GetString("D_LineMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Name.
        /// </summary>
        internal static string D_LineName {
            get {
                return ResourceManager.GetString("D_LineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        internal static string D_LineOperation {
            get {
                return ResourceManager.GetString("D_LineOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Special.
        /// </summary>
        internal static string D_LineSpecial {
            get {
                return ResourceManager.GetString("D_LineSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Status Rule.
        /// </summary>
        internal static string D_LineStatusRule {
            get {
                return ResourceManager.GetString("D_LineStatusRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Type.
        /// </summary>
        internal static string D_LineType {
            get {
                return ResourceManager.GetString("D_LineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Status.
        /// </summary>
        internal static string D_LinkStatus {
            get {
                return ResourceManager.GetString("D_LinkStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        internal static string D_Local {
            get {
                return ResourceManager.GetString("D_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material History.
        /// </summary>
        internal static string D_MaterialHistory {
            get {
                return ResourceManager.GetString("D_MaterialHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Status.
        /// </summary>
        internal static string D_MaterialStatus {
            get {
                return ResourceManager.GetString("D_MaterialStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MES Alive Link Test.
        /// </summary>
        internal static string D_MESAliveLinkTest {
            get {
                return ResourceManager.GetString("D_MESAliveLinkTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MES Alive Request.
        /// </summary>
        internal static string D_MESConnectionTest {
            get {
                return ResourceManager.GetString("D_MESConnectionTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor.
        /// </summary>
        internal static string D_Monitor {
            get {
                return ResourceManager.GetString("D_Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPLC Interlock.
        /// </summary>
        internal static string D_MPLCInterlock {
            get {
                return ResourceManager.GetString("D_MPLCInterlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EQP Control.
        /// </summary>
        internal static string D_NodeControl {
            get {
                return ResourceManager.GetString("D_NodeControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EQP History.
        /// </summary>
        internal static string D_NodeHistory {
            get {
                return ResourceManager.GetString("D_NodeHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EQP Status.
        /// </summary>
        internal static string D_NodeStatus {
            get {
                return ResourceManager.GetString("D_NodeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ODF Assembly History.
        /// </summary>
        internal static string D_ODFAssemblyHistory {
            get {
                return ResourceManager.GetString("D_ODFAssemblyHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ODF Track Time Setting.
        /// </summary>
        internal static string D_ODFTrackTimeSetting {
            get {
                return ResourceManager.GetString("D_ODFTrackTimeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string D_Off {
            get {
                return ResourceManager.GetString("D_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string D_On {
            get {
                return ResourceManager.GetString("D_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        internal static string D_Operator {
            get {
                return ResourceManager.GetString("D_Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPI History.
        /// </summary>
        internal static string D_OPIHistory {
            get {
                return ResourceManager.GetString("D_OPIHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        internal static string D_Parameter {
            get {
                return ResourceManager.GetString("D_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Setting.
        /// </summary>
        internal static string D_ParameterSetting {
            get {
                return ResourceManager.GetString("D_ParameterSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ELA Parameter Setting.
        /// </summary>
        internal static string D_ParameterSetting_ELA {
            get {
                return ResourceManager.GetString("D_ParameterSetting_ELA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLC TRX Data.
        /// </summary>
        internal static string D_PLCTrxData {
            get {
                return ResourceManager.GetString("D_PLCTrxData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Control.
        /// </summary>
        internal static string D_PortControl {
            get {
                return ResourceManager.GetString("D_PortControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Enable.
        /// </summary>
        internal static string D_PortEnable {
            get {
                return ResourceManager.GetString("D_PortEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port History.
        /// </summary>
        internal static string D_PortHistory {
            get {
                return ResourceManager.GetString("D_PortHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Mode.
        /// </summary>
        internal static string D_PortMode {
            get {
                return ResourceManager.GetString("D_PortMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Status.
        /// </summary>
        internal static string D_PortStatus {
            get {
                return ResourceManager.GetString("D_PortStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Transfer.
        /// </summary>
        internal static string D_PortTransfer {
            get {
                return ResourceManager.GetString("D_PortTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Type.
        /// </summary>
        internal static string D_PortType {
            get {
                return ResourceManager.GetString("D_PortType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPK Event Name History.
        /// </summary>
        internal static string D_PPKEventNameHistory {
            get {
                return ResourceManager.GetString("D_PPKEventNameHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Data.
        /// </summary>
        internal static string D_ProcessData {
            get {
                return ResourceManager.GetString("D_ProcessData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Data History.
        /// </summary>
        internal static string D_ProcessDataHistory {
            get {
                return ResourceManager.GetString("D_ProcessDataHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Data Management.
        /// </summary>
        internal static string D_ProcessDataManagement {
            get {
                return ResourceManager.GetString("D_ProcessDataManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Pause Command.
        /// </summary>
        internal static string D_ProcessPauseCommand {
            get {
                return ResourceManager.GetString("D_ProcessPauseCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Stop.
        /// </summary>
        internal static string D_ProcessStop {
            get {
                return ResourceManager.GetString("D_ProcessStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type Block.
        /// </summary>
        internal static string D_ProductTypeBlock {
            get {
                return ResourceManager.GetString("D_ProductTypeBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q Time Setting.
        /// </summary>
        internal static string D_QTimeSetting {
            get {
                return ResourceManager.GetString("D_QTimeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Time Glass Count.
        /// </summary>
        internal static string D_RealTimeGlassCount {
            get {
                return ResourceManager.GetString("D_RealTimeGlassCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe Management.
        /// </summary>
        internal static string D_RecipeManagement {
            get {
                return ResourceManager.GetString("D_RecipeManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross Line Recipe Management.
        /// </summary>
        internal static string D_RecipeManagementCross {
            get {
                return ResourceManager.GetString("D_RecipeManagementCross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe Paramater History.
        /// </summary>
        internal static string D_RecipeParamaterHistory {
            get {
                return ResourceManager.GetString("D_RecipeParamaterHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe Parameter.
        /// </summary>
        internal static string D_RecipeParameter {
            get {
                return ResourceManager.GetString("D_RecipeParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross Line Recipe Parameter.
        /// </summary>
        internal static string D_RecipeParameterCross {
            get {
                return ResourceManager.GetString("D_RecipeParameterCross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe Parameter Management.
        /// </summary>
        internal static string D_RecipeParameterManagement {
            get {
                return ResourceManager.GetString("D_RecipeParameterManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross Line Recipe Register.
        /// </summary>
        internal static string D_RecipeRegisterCorss {
            get {
                return ResourceManager.GetString("D_RecipeRegisterCorss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe Table History.
        /// </summary>
        internal static string D_RecipeTableHistory {
            get {
                return ResourceManager.GetString("D_RecipeTableHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string D_Reload {
            get {
                return ResourceManager.GetString("D_Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot Control.
        /// </summary>
        internal static string D_RobotControl {
            get {
                return ResourceManager.GetString("D_RobotControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RobotLayout.
        /// </summary>
        internal static string D_RobotLayout {
            get {
                return ResourceManager.GetString("D_RobotLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot Management.
        /// </summary>
        internal static string D_RobotManagement {
            get {
                return ResourceManager.GetString("D_RobotManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot Method Definition.
        /// </summary>
        internal static string D_RobotMethodDef {
            get {
                return ResourceManager.GetString("D_RobotMethodDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot Operation Mode.
        /// </summary>
        internal static string D_RobotOperationMode {
            get {
                return ResourceManager.GetString("D_RobotOperationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot Route.
        /// </summary>
        internal static string D_RobotRoute {
            get {
                return ResourceManager.GetString("D_RobotRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot Route Condition.
        /// </summary>
        internal static string D_RobotRouteCondition {
            get {
                return ResourceManager.GetString("D_RobotRouteCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot Route Master.
        /// </summary>
        internal static string D_RobotRouteMst {
            get {
                return ResourceManager.GetString("D_RobotRouteMst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot Rule Job Select.
        /// </summary>
        internal static string D_RobotRuleJobSelect {
            get {
                return ResourceManager.GetString("D_RobotRuleJobSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot Run Mode Management.
        /// </summary>
        internal static string D_RobotRunModeManagement {
            get {
                return ResourceManager.GetString("D_RobotRunModeManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot Stage Management.
        /// </summary>
        internal static string D_RobotStageManagement {
            get {
                return ResourceManager.GetString("D_RobotStageManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Mode.
        /// </summary>
        internal static string D_RunMode {
            get {
                return ResourceManager.GetString("D_RunMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sampling Rule.
        /// </summary>
        internal static string D_SamplingRule {
            get {
                return ResourceManager.GetString("D_SamplingRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SECS Function.
        /// </summary>
        internal static string D_SECSFunction {
            get {
                return ResourceManager.GetString("D_SECSFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SECS Variable Management.
        /// </summary>
        internal static string D_SECSVariableManagement {
            get {
                return ResourceManager.GetString("D_SECSVariableManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string D_Send {
            get {
                return ResourceManager.GetString("D_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string D_Setting {
            get {
                return ResourceManager.GetString("D_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Report Setting.
        /// </summary>
        internal static string D_SkipReportSetting {
            get {
                return ResourceManager.GetString("D_SkipReportSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot Information.
        /// </summary>
        internal static string D_SlotInformation {
            get {
                return ResourceManager.GetString("D_SlotInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Block.
        /// </summary>
        internal static string D_SubBlock {
            get {
                return ResourceManager.GetString("D_SubBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Calibration.
        /// </summary>
        internal static string D_TimeCalibration {
            get {
                return ResourceManager.GetString("D_TimeCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Calibration For All EQP.
        /// </summary>
        internal static string D_TimeCalibrationForallEQP {
            get {
                return ResourceManager.GetString("D_TimeCalibrationForallEQP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Out.
        /// </summary>
        internal static string D_TrackOut {
            get {
                return ResourceManager.GetString("D_TrackOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Stop.
        /// </summary>
        internal static string D_TransferStop {
            get {
                return ResourceManager.GetString("D_TransferStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit History.
        /// </summary>
        internal static string D_UnitHistory {
            get {
                return ResourceManager.GetString("D_UnitHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unloading Port Setting.
        /// </summary>
        internal static string D_UnloadingPortSetting {
            get {
                return ResourceManager.GetString("D_UnloadingPortSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Account.
        /// </summary>
        internal static string D_UserAccount {
            get {
                return ResourceManager.GetString("D_UserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change User Password.
        /// </summary>
        internal static string D_UserChangePwd {
            get {
                return ResourceManager.GetString("D_UserChangePwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Group.
        /// </summary>
        internal static string D_UserGroup {
            get {
                return ResourceManager.GetString("D_UserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Group Query.
        /// </summary>
        internal static string D_UserGroupQuery {
            get {
                return ResourceManager.GetString("D_UserGroupQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Login.
        /// </summary>
        internal static string D_UserLogin {
            get {
                return ResourceManager.GetString("D_UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCR Enable Mode.
        /// </summary>
        internal static string D_VCREnableMode {
            get {
                return ResourceManager.GetString("D_VCREnableMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCR Reader ON.
        /// </summary>
        internal static string D_VCRReaderON {
            get {
                return ResourceManager.GetString("D_VCRReaderON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCR Status.
        /// </summary>
        internal static string D_VCRStatus {
            get {
                return ResourceManager.GetString("D_VCRStatus", resourceCulture);
            }
        }
    }
}
