//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniOPI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=118.163.246.35;Initial Catalog=UNIBCS;User ID=sa;Password=UniWorkS229" +
            "8")]
        public string UNIBCSConnectionString {
            get {
                return ((string)(this["UNIBCSConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=REBECCA-VAIO\\SQLEXPRESS;Initial Catalog=UNIBCS;Integrated Security=Tr" +
            "ue")]
        public string UNIBCSConnectionString1 {
            get {
                return ((string)(this["UNIBCSConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=59.124.28.62,1434;Initial Catalog=UNIBCS;Persist Security Info=True;U" +
            "ser ID=sa;Password=unicom22988123")]
        public string UNIBCSConnectionString2 {
            get {
                return ((string)(this["UNIBCSConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=REBECCA-VAIO\\SQLEXPRESS;Initial Catalog=UNIBCS;Integrated Security=Tr" +
            "ue")]
        public string UNIBCSConnectionString3 {
            get {
                return ((string)(this["UNIBCSConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=59.124.28.62,1434;Initial Catalog=UNIBCS;Persist Security Info=True;U" +
            "ser ID=sa")]
        public string UNIBCSConnectionString4 {
            get {
                return ((string)(this["UNIBCSConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=59.124.28.62,1442;Initial Catalog=UNIBCS_t3;Persist Security Info=Tru" +
            "e;User ID=sa;Password=unicom22988123")]
        public string UNIBCS_t3ConnectionString {
            get {
                return ((string)(this["UNIBCS_t3ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=59.124.28.62,1442;Initial Catalog=UNIBCS_t3;Persist Security Info=Tru" +
            "e;User ID=sa")]
        public string UNIBCSConnectionString5 {
            get {
                return ((string)(this["UNIBCSConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=REX-PC;Initial Catalog=UNIBCS_t3;Persist Security Info=True;User ID=s" +
            "a")]
        public string UNIBCS_t3ConnectionString1 {
            get {
                return ((string)(this["UNIBCS_t3ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=REBECCA-PC\\SQLEXPRESS2012;Initial Catalog=UNIBCS_t3;Persist Security " +
            "Info=True;User ID=sa;Password=unicom22988123")]
        public string UNIBCS_t3ConnectionString2 {
            get {
                return ((string)(this["UNIBCS_t3ConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=59.124.28.62,1442;Initial Catalog=UNIBCS_t3;User ID=sa;Password=unico" +
            "m22988123")]
        public string UNIBCSConnectionString6 {
            get {
                return ((string)(this["UNIBCSConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;Initial Catalog=UNIBCS_t3;Persist Security Info=True;User I" +
            "D=sa")]
        public string UNIBCS_t3ConnectionString3 {
            get {
                return ((string)(this["UNIBCS_t3ConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=REBECCA-PC\\SQLEXPRESS2012;Initial Catalog=UNIBCS_t3;User ID=sa;Passwo" +
            "rd=unicom22988123")]
        public string UNIBCS_t3ConnectionString4 {
            get {
                return ((string)(this["UNIBCS_t3ConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=REBECCA-PC\\SQLEXPRESS2012;Initial Catalog=UNIBCS_t3;Persist Security " +
            "Info=True;User ID=sa")]
        public string UNIBCS_t3ConnectionString5 {
            get {
                return ((string)(this["UNIBCS_t3ConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=59.124.28.62,1442;Initial Catalog=UNIBCS_t3;Persist Security Info=Tru" +
            "e;User ID=sa")]
        public string UNIBCS_t3ConnectionString6 {
            get {
                return ((string)(this["UNIBCS_t3ConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MING-PC\\SQLEXPRESS;Initial Catalog=UNIBCS_t3;Persist Security Info=Tr" +
            "ue;User ID=sa;Password=sa")]
        public string UNIBCS_t3ConnectionString7 {
            get {
                return ((string)(this["UNIBCS_t3ConnectionString7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MARINE-PC;Initial Catalog=UNIBCS_t3;Persist Security Info=True;User I" +
            "D=sa")]
        public string UNIBCS_t3ConnectionString8 {
            get {
                return ((string)(this["UNIBCS_t3ConnectionString8"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MARINE-PC;Initial Catalog=UNIBCS_t3;Persist Security Info=True;User I" +
            "D=sa;Password=itc123!@#")]
        public string UNIBCS_t3ConnectionString9 {
            get {
                return ((string)(this["UNIBCS_t3ConnectionString9"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=NOBUHIKO-PC;Initial Catalog=UNIBCS_t3;User ID=sa;Password=itc123!@#")]
        public string UNIBCS_t3ConnectionString10 {
            get {
                return ((string)(this["UNIBCS_t3ConnectionString10"]));
            }
        }
    }
}
